### ISSUE TITLE
Build error on linux

### ISSUE THREAD

**Issue by SpyrosRoum** [jpochyla/psst#5]
I did the 
```sh
$ git submodule update --recursive --init
$ cargo build --release 
```
And then it failed with this lengthy error:
https://mystb.in/IntentNaplesCut.sql

**Comment by JojiiOfficial** [comment]
Having the same issue.

**Comment by gferon** [comment]
I have opened https://github.com/jpochyla/soundio-rs/pull/2 to be able to try `psst` out. 

You can try the fix out by adding the following to the root workspace `Cargo.toml`:

```toml
[patch."https://github.com/jpochyla/soundio-rs"]
soundio = { git = "https://github.com/gferon/soundio-rs", branch = "lib64-prefix" }
```

Depending on your distribution, you might need to install `libpulse-dev` and `libasound2-dev` (Debian based) or `libpulse-devel` and `alsa-lib-devel` (Fedora).
