### ISSUE TITLE
Run Action Builds in Parallel

### ISSUE THREAD

**Issue by shiftgeist** [jpochyla/psst#59]
It'd be great if the Debian build gets executed when the windows build fails. Sequential builds could also be interesting.

![image](https://user-images.githubusercontent.com/30648730/120012566-f3925d80-bfdf-11eb-8c03-9d702c285cab.png)
(from [psst/actions/runs/885002673](https://github.com/jpochyla/psst/actions/runs/885002673))

---

Edit:

Found this in the docs: `Example not requiring dependent jobs to be successful`

```yaml
jobs:
  job1:
  job2:
    needs: job1
  job3:
    if: always()
    needs: [job1, job2]
```

`needs` may not apply, but `if: always()` sounds promissing.

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-not-requiring-dependent-jobs-to-be-successful
